config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "users/index"
    get "users/edit"
    get "users/update"
    get "dashboard/index"
  end
  # get "home/index"
  root to: "home#index"

  resources :inventory_logs, only: [ :new, :create, :index ]

  resources :inventory_logs, only: [ :new, :create ]

  resources :products do
    collection do
      get :search
      post :import
    end
  end

  namespace :admin do
    get "dashboard", to: "dashboard#index"
    resources :users, only: [ :index, :edit, :update ]
  end

  get "reports", to: "reports#index"
  get "reports/fetch", to: "reports#fetch"

  post "/create-checkout-session", to: "checkout#create"

  get "/payment/success", to: "payments#success", as: :payment_success

  get "products/payment_cancelled", to: "products#payment_cancelled"

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  get "up" => "rails/health#show", as: :rails_health_check
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_flash.html.erb
<div class="container mt-4">
  <% flash.each do |key, message| %>
    <% alert_class = case key
       when "notice" then "alert-success"
       when "alert" then "alert-danger"
       else "alert-info"
       end
    %>

    <div class="alert <%= alert_class %> alert-dismissible fade show mt-4" role="alert">
      <%= message %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Inventory Management System", root_path, class: "navbar-brand" %>

<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

  <div class=" navbar-collapse show" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Products", products_path, class: 'nav-link' %>
        </li>

        <%# <% if can? :create, Product %>
          <%# <%= link_to 'New Product', new_product_path, class: 'nav-link' %>
        <%# <% end %>

        <% if policy(Product).new? %>
          <li class="nav-item">
            <%= link_to 'New Product', new_product_path, class: 'nav-link' %>
          </li>
        <% end %>

        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class: 'nav-link' %>
        </li>

        <li class="nav-item">
          <%= link_to "Stock In/Out", new_inventory_log_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Inventory History", inventory_logs_path, class: "nav-link" %>
        </li>

        <%# <% if can? :view_reports, :report %>
          <%# <li class="nav-item">
            # <%= link_to "View Reports", reports_path, class: "nav-link" %>
          <%# </li>
        <% end %> 

        <% if policy(:report).index? %>
          <%= link_to "View Reports", reports_path, class: 'nav-link' %>
        <% end %>
        

        <% if current_user&.admin? %>
          <li class="nav-item">
            <%= link_to "Admin Panel", admin_dashboard_path, class: "nav-link" %>
          </li>
        <% end %>


        <li class="nav-item">
          <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: "btn btn-link nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>

  </div>
</nav>

app/views/home/index.html.erb
<div>
  <h1>Welcome to Inventory System</h1>
  <p>Signed in as: <%= current_user.email %></p>
  <p>Your role: <%= current_user.role %></p>
</div>